Repository pmodels/mpich, pull requests merged in 2020-05, with the labels that each got.

#4475 ch4/ofi: Improved noncontiguous put/get
  src/include/mpir_datatype.h
  src/include/mpir_typerep.h
  src/mpi/datatype/typerep/src/typerep_dataloop_iov.c
  src/mpi/datatype/typerep/src/typerep_yaksa_iov.c
  src/mpid/ch4/netmod/ofi/ofi_impl.h
  src/mpid/ch4/netmod/ofi/ofi_init.c
  src/mpid/ch4/netmod/ofi/ofi_rma.h
  src/mpid/ch4/netmod/ofi/ofi_types.h
Labels: WIP

#4555 ch4: make MPIDI_Progress_test a wrapper for compatibility
  src/mpid/ch4/netmod/ofi/util.c
  src/mpid/ch4/shm/xpmem/xpmem_init.c
  src/mpid/ch4/src/ch4_impl.h
  src/mpid/ch4/src/ch4_progress.c
Labels: easy

#4556 warnings: pattern look like header guard
  src/mpid/ch4/shm/posix/eager/fbox/func_table.c
  src/mpid/ch4/shm/posix/eager/iqueue/func_table.c
  src/mpid/ch4/shm/posix/eager/stub/func_table.c
Labels: easy

#4391 ch4: initshm cleanup
  src/mpid/ch4/src/ch4_init.c
  src/mpid/common/shm/mpidu_init_shm.c
  src/mpid/common/shm/mpidu_init_shm.h
  src/mpid/common/shm/mpidu_init_shm_alloc.c
  src/mpl/configure.ac
Labels: ready-for-review
