Repository pmodels/mpich, pull requests merged in 2021-01, with the labels that each got.

#4904 MPI-4: implement MPI_Info_get_string()
  doc/refman/refmpi.tex
  maint/local_python/binding_c.py
  src/binding/c/info_api.txt
  src/binding/cxx/mpi.dat
  src/binding/fortran/mpif_h/buildiface
  src/binding/fortran/mpif_h/mpichf.def
  src/binding/fortran/mpif_h/mpichfg.def
  src/binding/fortran/mpif_h/mpichfs.def
  src/binding/fortran/use_mpi/buildiface
  src/binding/fortran/use_mpi_f08/mpi_c_interface_nobuf.f90
  src/binding/fortran/use_mpi_f08/mpi_f08.f90
  src/include/mpi.h.in
  src/mpi/info/info_impl.c
  test/mpi/.gitignore
  test/mpi/f08/info/Makefile.am
  test/mpi/f08/info/infogetstrf90.f90
  test/mpi/f08/info/testlist
  test/mpi/f77/info/Makefile.am
  test/mpi/f77/info/infogetstrf.f
  test/mpi/f77/info/testlist
  test/mpi/info/Makefile.am
  test/mpi/info/infogetstring.c
  test/mpi/info/testlist
Labels: ready-for-review

#4829 binding/f08: Use PMPI for internal type creation
  src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
Labels: controversial

#4758 datatype: ensure is_contig is consistent with yaksa
  src/include/mpir_typerep.h
  src/mpi/datatype/datatype_impl.c
  src/mpi/datatype/type_blockindexed.c
  src/mpi/datatype/type_create_pairtype.c
  src/mpi/datatype/type_dup.c
  src/mpi/datatype/typerep/src/typerep_dataloop_create.c
  src/mpi/datatype/typerep/src/typerep_yaksa_create.c
Labels: ready-for-review

#4986 gpu: consistently use MPIR_GPU_query_pointer_attr
  src/include/mpir_gpu.h
  src/mpi/coll/src/coll_impl.c
  src/mpi/datatype/typerep/src/typerep_yaksa_pack.c
  src/mpi/misc/utils.c
  src/mpid/ch4/src/ch4_impl.h
Labels: ready-for-review

#5012 MPI-4: deprecate MPI_Info_get and MPI_Info_get_valuelen
  src/binding/c/info_api.txt
Labels: easy

#4972 pt2pt: implement MPI_Isendrecv and MPI_Isendrecv_replace
  src/binding/c/pt2pt_api.txt
  src/binding/fortran/use_mpi_f08/wrappers_c/buildiface
  src/include/mpi.h.in
  src/mpi/pt2pt/sendrecv.c
  src/mpid/ch3/include/mpid_sched.h
  src/mpid/ch4/include/mpid_sched.h
  src/mpid/common/sched/mpidu_sched.c
  src/mpid/common/sched/mpidu_sched.h
  test/mpi/pt2pt/Makefile.am
  test/mpi/pt2pt/isendrecv.c
  test/mpi/pt2pt/isendrecv_replace.c
  test/mpi/pt2pt/sendrecv3.c
  test/mpi/pt2pt/testlist.in
Labels: ready-for-review
