Repository pmodels/mpich, pull requests merged in 2024-12, with the labels that each got.

#7231 ch4/spawn: enhance error reporting
  src/mpid/ch4/src/ch4_spawn.c
  src/mpid/common/bc/mpidu_bc.h
Labels: 4.3.x

#7239 mpi.h: Move stdint header inclusion outside of extern C block
  src/include/mpi.h.in
Labels: cc: stable

#7223 ch4/ofi: sparsely poll global progress in MPIDI_OFI_retry_progress
  src/mpid/ch4/netmod/ofi/ofi_impl.h
  src/mpid/ch4/netmod/ofi/util.c
Labels: aurora

#7244 mpi.h: adding back f2c/c2f macros
  src/include/mpi.h.in
Labels: ABI, 4.3.x
